contact:
  address: ""
  email: ""
  phone: ""
plugins:
  - jekyll-feed
  - jekyll-seo-tag
title: AMSAT Canada
description: The Canadian Amateur Satellite Organization
logo: assets/media/logos/logo.svg
footer_logo: assets/media/logos/logo.svg
baseurl: ""
url: https://amsat-ca.org
socials:
  - name: LinkedIn
    url: https://www.linkedin.com/company/amsat-canada/
    icon: linkedin
  - icon: github
    name: Github
    url: https://github.com/AMSAT-CA
include:
  - admin
footer:
  show_contact: false
  show_social: true
web3forms:
  access_key: b8ed0752-98a5-4f19-8f4a-8c6c58953e9e
  subject: Contact Form Submission from AMSAT-CA
  hcaptcha_sitekey: 50b2fe65-b00b-4b9e-ad62-3ba471098be2
theme: arbutus-theme
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
